"""CCTV 도메인 프롬프트"""

from .cctv_domain import (
    CCTV_BLOG_SYSTEM_PROMPT,
    OUTLINE_GENERATION_PROMPT,
    SECTION_GENERATION_PROMPT,
    INTRO_HOOK_PROMPT,
    CTA_GENERATION_PROMPT,
    TITLE_GENERATION_PROMPT,
    META_DESCRIPTION_PROMPT,
    TAGS_GENERATION_PROMPT,
    TARGET_AUDIENCE_PERSONAS,
    TEMPLATE_STRUCTURES,
)

__all__ = [
    "CCTV_BLOG_SYSTEM_PROMPT",
    "OUTLINE_GENERATION_PROMPT",
    "SECTION_GENERATION_PROMPT",
    "INTRO_HOOK_PROMPT",
    "CTA_GENERATION_PROMPT",
    "TITLE_GENERATION_PROMPT",
    "META_DESCRIPTION_PROMPT",
    "TAGS_GENERATION_PROMPT",
    "TARGET_AUDIENCE_PERSONAS",
    "TEMPLATE_STRUCTURES",
]
